### PR TITLE
adding OpenGL/DX11 interop and other improvements

### PR DESCRIPTION
**Pull request by ph0b**
Hi,

@ishmael1985 and I have worked on a new (quite big in the end!) set of changes.

The overall changes are:
- OpenGL - DirectX 11 interop for sinks on Windows
- OpenGL interop optimizations on Linux
- HEVC 10bpc encode support on Windows
- plugin activation only on compatible systems, for a better gstreamer plugins infrastructure integration
- overall codebase cleanups and fixes.

Regards,
Xavier.

### CODE REVIEW

**Comment by ph0b** [comment]
@ishmael1985 you mean about the last bitstream-copy optimization for VP8/VP9/MJPEG? 
Since mjpeg/vp8/vp9 decoders all expect complete frames and eat up all the bitstream you throw at them, I'm confident it's supposed to work. It's a simple fix in the end and it works with all the content I've got, so yes, I've pushed it :)
For the rest, the whole set of changes needs to be tested anyway, I don't have an extensive test suite on my end.

**Comment by ishmael1985** [comment]
Ok sure. In any case, if there's a problem we can easily fall back to bitstream copy for VP8 / VP9 / MJPEG decode after testing. The rest of the changes are all good, I tested it rather thoroughly :)

**Comment by ishmael1985** [comment]
Some bad news. With 6f004ff VP8 / VP9 / MJPEG seeking doesn't work! Roll this one  back a bit.

**Comment by ph0b** [comment]
ok I've put this change to a separate branch for now, I'll debug the seeking issue later.. and use MIN instead of min :)

**Comment by ishmael1985** [comment]
Too bad, this was a retreat from a great optimization, but I think with a bit of work, the seeking behaviour can be fixed.

**Pull request merged**
