### PR TITLE
big simplifications

### PR DESCRIPTION
**Pull request by ph0b**
we've done more cleanups and removed vc1 parsers.

### CODE REVIEW

**Comment by ishmael1985** [comment]
Err.... don't forget the last one on my repo :D

**Comment by ph0b** [comment]
@ishmael1985 ok! I've just added it too, thanks :)

**Comment by ishmael1985** [comment]
Sorry, I have a change of heart on one of the cleanups :D Can you fetch the latest commit from my repo and include in this pull request?

**Comment by ph0b** [comment]
done!

**Comment by ishmael1985** [comment]
All good to go then!

**Comment by ishmael1985** [comment]
Latest changes have been validated to work well on the Linux platform. Good stuff!

**Pull request merged**
